spring:
  profiles:
    active: local # 기본적으로 local이 선택된다는 뜻
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/sb_c_2022?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: test
    password: test
mybatis:
  type-aliases-package: com.nyj.exam.demo.vo
custom:
  logging:
    dir: log
    level: debug

---

spring:
  config:
    activate:
      on-profile: local
server:
  port: 8012

---

spring:
  config:
    activate:
      on-profile: production
  servlet:
    multipart: 
      location: /tmp #임시파일저장위치
  datasource:
    username: sbsstlocal
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/sb_c_2022_production?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
custom:
  logging:
    dir: /tmp/sb_c_2022-log
    level: info